### ISSUE TITLE
Error message when command is created when Helix angle is 0

### ISSUE THREAD

**Issue by phossystems** [NicoSchlueter/HelicalGear#8]
An error message appears when the Helix Angle is set to 0 when the command is created.

<img width="405" alt="message" src="https://user-images.githubusercontent.com/30301307/72370111-cf432300-3701-11ea-9345-83a059c948ce.png">

```
Traceback (most recent call last):
  File "/Users/nicoschluter/Projects/HelicalGear/Fission/fission.py", line 218, in notify
    callback(*args)
  File "/Users/nicoschluter/Projects/HelicalGear/Fission/fission.py", line 363, in __on_create
    self.initialize_inputs(self.input_factory)
  File "/Users/nicoschluter/Projects/HelicalGear/HelicalGear.py", line 751, in initialize_inputs
    self.update_warnings()
  File "/Users/nicoschluter/Projects/HelicalGear/HelicalGear.py", line 765, in update_warnings
    gear = self.make_gear()
  File "/Users/nicoschluter/Projects/HelicalGear/HelicalGear.py", line 888, in make_gear
    self.helix_angle.eval(),
  File "/Users/nicoschluter/Projects/HelicalGear/Fission/fission.py", line 502, in <lambda>
    input.eval = lambda: um.evaluateExpression(input.expression, units)
  File "/Users/nicoschluter/Library/Application Support/Autodesk/webdeploy/production/1235e987d853b6f5773abdcdd7ff0ff6bea9a707/Autodesk Fusion 360.app/Contents/Api/Python/packages/adsk/core.py", line 24479, in _get_expression
    return _core.ValueCommandInput__get_expression(self)
RuntimeError: 2 : InternalValidationError : res


```

**Comment by lhns** [comment]
Fixed in #10
